# Generated by Django 3.2.16 on 2022-12-01 07:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simplelabel', '0010_rename_datase_active_dataset_dataset_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='API_keys',
            fields=[
                ('api_key_name', models.CharField(max_length=100, unique=True)),
                ('api_key', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('api_key_level', models.IntegerField(default=0)),
            ],
        ),
    ]
