# Generated by Django 3.2.16 on 2022-12-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplelabel', '0012_rename_api_keys_api_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='API_key',
            new_name='ApiKey',
        ),
    ]
