# Generated by Django 3.2.18 on 2023-03-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplelabel', '0013_rename_api_key_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
