# Generated by Django 3.2.18 on 2023-03-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplelabel', '0014_class_class_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_is_active',
            new_name='class_is_visible',
        ),
    ]
