# Generated by Django 3.2.18 on 2023-03-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplelabel', '0015_rename_class_is_active_class_class_is_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('image',)},
        ),
    ]
