# Generated by Django 4.1.7 on 2023-03-21 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplelabel', '0018_auto_20230309_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_duplicate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate', to='simplelabel.image'),
        ),
    ]
