# Generated by Django 3.2.18 on 2023-03-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplelabel', '0018_auto_20230309_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_original_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
