# Generated by Django 3.2.15 on 2022-08-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplelabel', '0003_auto_20220818_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='images/%Y/%m/%d/', width_field='image_width'),
        ),
    ]
