# Generated by Django 3.2.15 on 2022-08-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplelabel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classes',
            new_name='Class',
        ),
    ]
