# Generated by Django 3.2.15 on 2022-08-18 08:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simplelabel', '0002_rename_classes_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AddField(
            model_name='image',
            name='image_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_height',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_width',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.RenameModel(
            old_name='Properties',
            new_name='Property',
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_date', models.DateTimeField(auto_now_add=True)),
                ('poll_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('poll_class', models.ManyToManyField(blank=True, to='simplelabel.Class')),
                ('poll_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplelabel.image')),
                ('poll_property', models.ManyToManyField(blank=True, to='simplelabel.Property')),
            ],
        ),
    ]
