# Generated by Django 3.2.15 on 2022-08-19 08:07

from django.db import migrations
import simplelabel.utils


class Migration(migrations.Migration):

    dependencies = [
        ('simplelabel', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_color',
            field=simplelabel.utils.HexField(default='00FF00'),
        ),
    ]
