# Generated by Django 3.2.15 on 2022-08-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplelabel', '0007_class_class_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_id',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
