# Generated by Django 3.2.16 on 2022-12-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplelabel', '0011_api_keys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='API_keys',
            new_name='API_key',
        ),
    ]
