# Generated by Django 3.2.18 on 2023-03-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplelabel', '0016_alter_image_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('image_name',)},
        ),
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
